site_name: xinj 个人网站

nav:
  - Home: index.md
  - About: about.md
  - Test: test.md
  - Notes:
      - 总览: notes/notes.md
      - 王夫之: notes/王夫之.md
  - Research:
      - AIGC版权: Research/AIGC Copyright.md

theme:
  name: 'material'
  favicon: img/1f537.svg
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
  toc_depth: 1  
  palette:
    - scheme: slate         
      primary: light-green
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: 切换到日间模式
    - scheme: default
      primary: light-green
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到夜间模式



  highlightjs: true
  hljs_languages:
    - yaml
    - rust

plugins:
  - search:
      lang:
        - ja
      separator: '[\s\u200b\-]'

# Chinese search support: https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/?h=%E4%B8%AD%E6%96%87

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  homepage: /
